spring.datasource.url=${URL}
spring.datasource.username=${USER}
spring.datasource.password=${PASSWORD}

spring.application.name=centimo-back-api

# Docker local (default)
spring.datasource.url=jdbc:postgresql://localhost:5432/centimo
spring.datasource.username=centimo
spring.datasource.password=centimo
spring.datasource.driver-class-name=org.postgresql.Driver

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.jpa.hibernate.ddl-auto=validate
